/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Go To Chapter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.GoToChapter#getChapterId <em>Chapter Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.GoToChapter#getEntrance <em>Entrance</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGoToChapter()
 * @model
 * @generated
 */
public interface GoToChapter extends EObject
{
  /**
   * Returns the value of the '<em><b>Chapter Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chapter Id</em>' reference.
   * @see #setChapterId(Chapter)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGoToChapter_ChapterId()
   * @model
   * @generated
   */
  Chapter getChapterId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.GoToChapter#getChapterId <em>Chapter Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chapter Id</em>' reference.
   * @see #getChapterId()
   * @generated
   */
  void setChapterId(Chapter value);

  /**
   * Returns the value of the '<em><b>Entrance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Entrance</em>' reference.
   * @see #setEntrance(StartPoint)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getGoToChapter_Entrance()
   * @model
   * @generated
   */
  StartPoint getEntrance();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.GoToChapter#getEntrance <em>Entrance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Entrance</em>' reference.
   * @see #getEntrance()
   * @generated
   */
  void setEntrance(StartPoint value);

} // GoToChapter
