/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getText <em>Text</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getChoices <em>Choices</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Scenario#getGoto <em>Goto</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario()
 * @model
 * @generated
 */
public interface Scenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Scenario#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Text</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' containment reference.
   * @see #setText(Text)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_Text()
   * @model containment="true"
   * @generated
   */
  Text getText();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Scenario#getText <em>Text</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' containment reference.
   * @see #getText()
   * @generated
   */
  void setText(Text value);

  /**
   * Returns the value of the '<em><b>Choices</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Choice}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Choices</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_Choices()
   * @model containment="true"
   * @generated
   */
  EList<Choice> getChoices();

  /**
   * Returns the value of the '<em><b>Goto</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Goto</em>' containment reference.
   * @see #setGoto(GoToChapter)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getScenario_Goto()
   * @model containment="true"
   * @generated
   */
  GoToChapter getGoto();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Scenario#getGoto <em>Goto</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Goto</em>' containment reference.
   * @see #getGoto()
   * @generated
   */
  void setGoto(GoToChapter value);

} // Scenario
