/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Start Point</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.StartPoint#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.StartPoint#getScenarioId <em>Scenario Id</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStartPoint()
 * @model
 * @generated
 */
public interface StartPoint extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStartPoint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.StartPoint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Scenario Id</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Scenario Id</em>' reference.
   * @see #setScenarioId(Scenario)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getStartPoint_ScenarioId()
   * @model
   * @generated
   */
  Scenario getScenarioId();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.StartPoint#getScenarioId <em>Scenario Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Scenario Id</em>' reference.
   * @see #getScenarioId()
   * @generated
   */
  void setScenarioId(Scenario value);

} // StartPoint
