/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.Chapter;
import org.xtext.example.mydsl.myDsl.GoToChapter;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.StartPoint;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Go To Chapter</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GoToChapterImpl#getChapterId <em>Chapter Id</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.GoToChapterImpl#getEntrance <em>Entrance</em>}</li>
 * </ul>
 *
 * @generated
 */
public class GoToChapterImpl extends MinimalEObjectImpl.Container implements GoToChapter
{
  /**
   * The cached value of the '{@link #getChapterId() <em>Chapter Id</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChapterId()
   * @generated
   * @ordered
   */
  protected Chapter chapterId;

  /**
   * The cached value of the '{@link #getEntrance() <em>Entrance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEntrance()
   * @generated
   * @ordered
   */
  protected StartPoint entrance;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected GoToChapterImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.GO_TO_CHAPTER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Chapter getChapterId()
  {
    if (chapterId != null && chapterId.eIsProxy())
    {
      InternalEObject oldChapterId = (InternalEObject)chapterId;
      chapterId = (Chapter)eResolveProxy(oldChapterId);
      if (chapterId != oldChapterId)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID, oldChapterId, chapterId));
      }
    }
    return chapterId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Chapter basicGetChapterId()
  {
    return chapterId;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChapterId(Chapter newChapterId)
  {
    Chapter oldChapterId = chapterId;
    chapterId = newChapterId;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID, oldChapterId, chapterId));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StartPoint getEntrance()
  {
    if (entrance != null && entrance.eIsProxy())
    {
      InternalEObject oldEntrance = (InternalEObject)entrance;
      entrance = (StartPoint)eResolveProxy(oldEntrance);
      if (entrance != oldEntrance)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.GO_TO_CHAPTER__ENTRANCE, oldEntrance, entrance));
      }
    }
    return entrance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StartPoint basicGetEntrance()
  {
    return entrance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEntrance(StartPoint newEntrance)
  {
    StartPoint oldEntrance = entrance;
    entrance = newEntrance;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.GO_TO_CHAPTER__ENTRANCE, oldEntrance, entrance));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID:
        if (resolve) return getChapterId();
        return basicGetChapterId();
      case MyDslPackage.GO_TO_CHAPTER__ENTRANCE:
        if (resolve) return getEntrance();
        return basicGetEntrance();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID:
        setChapterId((Chapter)newValue);
        return;
      case MyDslPackage.GO_TO_CHAPTER__ENTRANCE:
        setEntrance((StartPoint)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID:
        setChapterId((Chapter)null);
        return;
      case MyDslPackage.GO_TO_CHAPTER__ENTRANCE:
        setEntrance((StartPoint)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.GO_TO_CHAPTER__CHAPTER_ID:
        return chapterId != null;
      case MyDslPackage.GO_TO_CHAPTER__ENTRANCE:
        return entrance != null;
    }
    return super.eIsSet(featureID);
  }

} //GoToChapterImpl
